fps: 30

robot:
  type: bi_widowxai_follower_robot
  id: bimanual_follower

  left_arm_max_relative_target: null
  right_arm_max_relative_target: null
  min_time_to_move_multiplier: 3.0
  loop_rate: 30

  include_velocity: false
  include_effort: false
  include_external_effort: false

  cameras:
    cam_high:
      type: intelrealsense
      width: 424
      height: 240
      fps: 15

    cam_low:
      type: intelrealsense
      width: 424
      height: 240
      fps: 15

    cam_left_wrist:
      type: intelrealsense
      width: 424
      height: 240
      fps: 15

    cam_right_wrist:
      type: intelrealsense
      width: 424
      height: 240
      fps: 15

teleop:
  type: bi_widowxai_leader_teleop
  id: bimanual_leader

display_data: true
